# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: "ubuntu-22.04"

strategy:
  matrix:
    node_22_x:
      node_version: 22.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js

  - bash: npm install
    displayName: Install dependencies

  - bash: npm run build
    displayName: Lint and Build TypeScript

  - bash: npm run test:coverage
    displayName: Test

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "coverage/lcov.info"
      testRunTitle: TestRun $(node_version)
