# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: "ubuntu-16.04"

strategy:
  matrix:
    node_12_x:
      node_version: 12.x
    node_14_x:
      node_version: 14.x
    node_16_x:
      node_version: 16.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js

  - bash: npm install
    displayName: Install dependencies

  - bash: npm run build
    displayName: Lint and Build TypeScript

  - bash: npm run test:report && npm run test:reporter
    displayName: Test

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "junit-testresults.xml"
      testRunTitle: TestRun $(node_version)
